# Generated by Django 2.2.3 on 2019-07-13 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnovate', '0003_auto_20190714_0217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='vid',
            new_name='file',
        ),
    ]
