# Generated by Django 2.0.1 on 2019-07-14 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learnovate', '0005_video_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='resource',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='learnovate.Resource'),
        ),
    ]
